apiVersion: v1
kind: ConfigMap
metadata:
  name: asset-tracker-config
  namespace: asset-tracker
data:
  GO_PORT: "8080"
  NODE_PORT: "3000"
  KAFKA_BROKER: "kafka-service:9092"
  KAFKA_TOPIC: "device-events"
  POSTGRES_DB: "asset_tracker"
  MONGO_DB: "asset_tracker"
  JWT_EXPIRATION: "1h"
  API_GO_URL: "http://go-service:8080"
  API_NODE_URL: "http://node-service:3000"
