---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: asset-tracker
  labels:
    app: web-ui
spec:
  type: ClusterIP
  selector:
    app: web-ui
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
