/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesCreateRouteImport } from './routes/devices.create'
import { Route as DevicesIdRouteImport } from './routes/devices.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesCreateRoute = DevicesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DevicesRoute,
} as any)
const DevicesIdRoute = DevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DevicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboards': typeof DashboardsRoute
  '/devices': typeof DevicesRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/devices/$id': typeof DevicesIdRoute
  '/devices/create': typeof DevicesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboards': typeof DashboardsRoute
  '/devices': typeof DevicesRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/devices/$id': typeof DevicesIdRoute
  '/devices/create': typeof DevicesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboards': typeof DashboardsRoute
  '/devices': typeof DevicesRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/devices/$id': typeof DevicesIdRoute
  '/devices/create': typeof DevicesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboards'
    | '/devices'
    | '/events'
    | '/login'
    | '/devices/$id'
    | '/devices/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboards'
    | '/devices'
    | '/events'
    | '/login'
    | '/devices/$id'
    | '/devices/create'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboards'
    | '/devices'
    | '/events'
    | '/login'
    | '/devices/$id'
    | '/devices/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardsRoute: typeof DashboardsRoute
  DevicesRoute: typeof DevicesRouteWithChildren
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/create': {
      id: '/devices/create'
      path: '/create'
      fullPath: '/devices/create'
      preLoaderRoute: typeof DevicesCreateRouteImport
      parentRoute: typeof DevicesRoute
    }
    '/devices/$id': {
      id: '/devices/$id'
      path: '/$id'
      fullPath: '/devices/$id'
      preLoaderRoute: typeof DevicesIdRouteImport
      parentRoute: typeof DevicesRoute
    }
  }
}

interface DevicesRouteChildren {
  DevicesIdRoute: typeof DevicesIdRoute
  DevicesCreateRoute: typeof DevicesCreateRoute
}

const DevicesRouteChildren: DevicesRouteChildren = {
  DevicesIdRoute: DevicesIdRoute,
  DevicesCreateRoute: DevicesCreateRoute,
}

const DevicesRouteWithChildren =
  DevicesRoute._addFileChildren(DevicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardsRoute: DashboardsRoute,
  DevicesRoute: DevicesRouteWithChildren,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
